export default {
  login: "davemarquez20",
  id: 52246960,
  node_id: "MDQ6VXNlcjUyMjQ2OTYw",
  avatar_url: "https://avatars.githubusercontent.com/u/52246960?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/davemarquez20",
  html_url: "https://github.com/davemarquez20",
  followers_url: "https://api.github.com/users/davemarquez20/followers",
  following_url:
    "https://api.github.com/users/davemarquez20/following{/other_user}",
  gists_url: "https://api.github.com/users/davemarquez20/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/davemarquez20/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/davemarquez20/subscriptions",
  organizations_url: "https://api.github.com/users/davemarquez20/orgs",
  repos_url: "https://api.github.com/users/davemarquez20/repos",
  events_url: "https://api.github.com/users/davemarquez20/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/davemarquez20/received_events",
  type: "User",
  site_admin: false,
  name: "Mark Dave Marquez",
  company: null,
  blog: "mdmarquez.online",
  location: null,
  email: "davemarquez20@outlook.com",
  hireable: null,
  bio: "This is my bio",
  twitter_username: "emdee5566",
  public_repos: 16,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2019-06-26T13:27:38Z",
  updated_at: "2022-12-05T11:49:34Z",
};
